application:
    api:
        swagger:
            path: /api-docs/swagger
            version: 3.19.4
            layout: StandaloneLayout
            deepLinking: true
            urls:
            - name: micronaut
              url: /api-docs/swagger/micronaut-0.0.1.yml
micronaut:
    application:
        name: micronaut-service
        instance: ${random.uuid}
        version: 0.1
    server:
        port: 9090
        netty:
          log-level: TRACE        
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: ${application.api.swagger.path}/**

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true

endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
        url:
            enabled: true
eureka:
  client:
    registration:
      enabled: false
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"            
